title: Your awesome title
author: GitHub User
email: hanna2mazur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Perfect design for your business
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Hanna2m # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
